app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/generate/models', '\\Jimbolino\\Laravel\\ModelBuilder\\ModelGenerator5@start');

//-- Frontend Routes --//
Route::get('/', [
    'as' => 'index',
	'uses' => 'PageController@index'
]);
Route::get('/blog', [
    'as' => 'blog',
	'uses' => 'NewsController@index'
]);
Route::get('/blog/{new}', [
    'as' => 'news.show',
	'uses' => 'NewsController@show'
]);

	/*************************/
	/*	PACO */
	/*************************/

	//COMO FUNCIONA
	Route::get('/como-funciona', function(){
		return view('frontend.pages.como');
	});

	//EMRPESA
	Route::get('/empresas', function(){
		return view('frontend.pages.empresas');
	});

	//INVERSORES
	Route::get('/inversores', function(){
		return view('frontend.pages.inversores');
	});

	//REGISTRO INVERSORES
	Route::get('/registro-inversor', function() {
		return view('auth.registro-inversor');
	});
	Route::post('/registro-inversor', [
		'as' => 'register_investor',
		'uses' => 'UserController@registerInvestor'
	]);

	//REGISTRO EMPRESAS
	Route::get('/registro-empresa', function() {
		return view('auth.registro-empresa');
	});
	Route::post('/registro-empresa', [
		'as' => 'register_company',
		'uses' => 'UserController@registerComapny'
	]);

	//CASOS EXITO INVERSORES
	Route::get('/casos-de-exito-inversores', function(){
		return view('frontend.pages.casos-exito-inversores');
	});

	//CASOS EXITO EMPRESASA
	Route::get('/casos-de-exito-empresa', function(){
		return view('frontend.pages.casos-exito-empresa');
	});

	//BLOG DETALLE (temporal para maquetarlo)
	Route::get('/blog/view', function(){
		return view('frontend.news.view');
	});

	//CASOS EXITO
	Route::get('/casos-de-exito', [
			'as' => 'success_cases.index',
			'uses' => 'PageController@success_cases'
	]);
	Route::get('/caso-de-exito/{case}', [
			'as' => 'success_cases.show',
			'uses' => 'PageController@success_cases'
	]);

	/*************************/
	/*	END PACO */
	/*************************/

///-- Profile Routes --///
Route::group(['middleware' => 'auth'], function () {
	Route::get('/perfil/editar', [
		'as' => 'profileEdit',
		'uses' => 'UserController@profileEdit'
	]);

	Route::get('perfil', [
		'as' => 'profile',
		'uses' => 'UserController@profile'
	]);

	Route::post('perfil/editar', [
		'as' => 'profile.update',
		'uses' => 'UserController@updateProfile'
	]);
});
///-- /Profile Routes --///
//-- /Frontend Routes --//

//-- Auth Routes --//
Route::get('auth/login', [
	'as' => 'auth.login',
	'uses' => 'Auth\AuthController@getLogin'
]);
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', [
	'as' => 'auth.logout',
	'uses' => 'Auth\AuthController@getLogout'
]);

Route::get('auth/register', [
    'as' => 'auth.register',
	'uses' => 'Auth\AuthController@getRegister'
]);

// Route::post('auth/register', 'Auth\AuthController@postRegister');
Route::post('auth/registro', [
	'as' => 'auth.register.postRegister',
	'uses' => 'Auth\AuthController@postRegister'
	// 'uses' => 'UserController@register'
]);

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');
//-- /Auth Routes --//

Route::group([
	'prefix' => 'area-privada',
	'namespace' => 'PrivateArea',
	'middleware' => ['auth']
], function () {

	Route::get('/', [
		'as' => 'private.users.index',
		'uses' => 'UserController@index'
	]);

	//- Inversor - //
	Route::get('inversor', [
		'as' => 'private.investors.profile',
		'uses' => 'InvestorController@profile'
	]);
	Route::put('inversor', [
		'as' => 'private.investors.update',
		'uses' => 'InvestorController@update'
	]);
	Route::get('wallet/{substract?}', [
		'as' => 'private.investors.wallet',
		'uses' => 'InvestorController@wallet'
	]);
	Route::get('propuestas-de-inversion', [
		'as' => 'private.investors.proposals',
		'uses' => 'InvestorController@proposals'
	]);
	Route::get('historico', [
		'as' => 'private.investors.historical',
		'uses' => 'InvestorController@historical'
	]);
	Route::post('historico', [
		'as' => 'private.investors.historical',
		'uses' => 'InvestorController@historical'
	]);
	//- /Inversor - //

	//- Transfers - //
	Route::put('transfer/{substract?}', [
		'as' => 'private.transfers.store',
		'uses' => 'TransferController@store'
	]);
	//- /Trasnfers - //

	//- Notification - //
	Route::get('notificaciones', [
		'as' => 'private.notifications.index',
		'uses' => 'NotificationController@index'
	]);
	//- /Notification - //

	//- Inversor - //
	Route::get('empresa', [
		'as' => 'private.transferor_companies.profile',
		'uses' => 'TransferorCompanyController@profile'
	]);
	Route::put('empresa', [
		'as' => 'private.transferor_companies.update',
		'uses' => 'TransferorCompanyController@update'
	]);
	Route::get('presupuestos', [
		'as' => 'private.transferor_companies.invoices',
		'uses' => 'TransferorCompanyController@invoices'
	]);
	//- /Inversor - //

	//- Invoices - //
	Route::put('presupuestos', [
		'as' => 'private.invoices.store',
		'uses' => 'InvoiceController@store'
	]);
	Route::get('presupuesto/{invoice}', [
		'as' => 'private.invoices.view',
		'uses' => 'InvoiceController@view'
	]);
	//- /Invoices - //

	//- Operations - //
	Route::get('operacion/aceptar-propuesta/{operation}', [
		'as' => 'private.operations.accept-proposal',
		'uses' => 'OperationController@acceptProposal'
	]);
	Route::get('operacion/rechazar-propuesta/{operation}', [
		'as' => 'private.operations.reject-proposal',
		'uses' => 'OperationController@rejectProposal'
	]);
	Route::post('operacion/rechazando-propuesta/{operation}', [
		'as' => 'private.operations.reject-proposal-post',
		'uses' => 'OperationController@rejectProposal'
	]);
	Route::get('operacion/invertir/{operation}', [
		'as' => 'private.operations.invest',
		'uses' => 'OperationController@invest'
	]);
	Route::post('operacion/invertir/{operation}', [
		'as' => 'private.operations.invest',
		'uses' => 'OperationController@invest'
	]);
	Route::get('operacion/rechazar/{operation}', [
		'as' => 'private.operations.reject',
		'uses' => 'OperationController@reject'
	]);
	//- /Operations - //

});

Route::group([
	'prefix' => 'admin',
	'namespace' => 'Admin',
	'middleware' => ['admin', 'auth']
], function () {

	Route::get('/', [
		'as' => 'admin.index',
		'uses' => 'DashboardController@index'
	]);

   //-- Users Routes --//
    Route::get('usuarios/{type?}', [
        'as' => 'admin.users.index',
        'uses' => 'UserController@index'
    ]);

    Route::get('usuario/crear', [
        'as' => 'admin.users.create',
        'uses' => 'UserController@create'
    ]);

    Route::get('usuario/{user}/editar', [
        'as' => 'admin.users.edit',
        'uses' => 'UserController@edit'
    ]);

    Route::post('usuarios', [
        'as' => 'admin.users.store',
        'uses' => 'UserController@store'
    ]);

    Route::delete('usuario/{user}', [
        'as' => 'admin.users.destroy',
        'uses' => 'UserController@destroy'
    ]);

    Route::put('usuario/{user}', [
        'as' => 'admin.users.update',
        'uses' => 'UserController@update'
    ]);

    Route::post('usuario/{user}/ban', [
        'as' => 'admin.users.ban',
        'uses' => 'UserController@ban'
    ]);

    Route::post('usuario/{user}/unban', [
        'as' => 'admin.users.unban',
        'uses' => 'UserController@unban'
    ]);
    //-- /Users Routes --//

    //-- Notifications Routes --//
	Route::get('notificaciones', [
		'as' => 'admin.notifications.index',
		'uses' => 'NotificationController@index'
	]);
    //-- /Notifications Routes --//

    //-- Transfers Routes --//
    Route::get('transferencias', [
        'as' => 'admin.transfers.index',
        'uses' => 'TransferController@index'
    ]);
    // Route::get('transferencia/crear', [
    //     'as' => 'admin.transfers.create',
    //     'uses' => 'TransferController@create'
    // ]);
    // Route::post('transferencias', [
    //     'as' => 'admin.transfers.store',
    //     'uses' => 'TransferController@store'
    // ]);
    // Route::put('transferencia/{transfer}', [
    //     'as' => 'admin.transfers.update',
    //     'uses' => 'TransferController@update'
    // ]);
    Route::get('transferencia/{transfer}/editar/{cancel?}', [
        'as' => 'admin.transfers.edit',
        'uses' => 'TransferController@edit'
    ]);
	// Route::delete('transferencia/{transfer}', [
	// 	'as' => 'admin.transfers.destroy',
	// 	'uses' => 'TransferController@destroy'
	// ]);
    //-- /Transfers Routes --//

	//-- Operations Routes --//
    Route::get('operaciones', [
        'as' => 'admin.operations.index',
        'uses' => 'OperationController@index'
    ]);
    Route::get('operacion/{operation}/editar', [
        'as' => 'admin.operations.edit',
        'uses' => 'OperationController@edit'
    ]);
    Route::get('operacion/{operation}', [
        'as' => 'admin.operations.show',
        'uses' => 'OperationController@show'
    ]);
    Route::post('operacion/loan_status/{operation}', [
        'as' => 'admin.operations.updateStatus',
        'uses' => 'OperationController@updateStatus'
    ]);
    //-- /Operations Routes --//


    //-- Pages Routes --//
    Route::get('paginas', [
        'as' => 'admin.pages.index',
        'uses' => 'PageController@index'
    ]);
    Route::get('pagina/crear', [
        'as' => 'admin.pages.create',
        'uses' => 'PageController@create'
    ]);
    Route::post('paginas', [

app/Models/News.php
<?php

namespace App\Models;

use App\Models\BaseModel;

/**
 * Eloquent class to describe the news table
 *
 * automatically generated by ModelGenerator.php
 */
class News extends BaseModel
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'news';

    /**
     * All date fields of the model.
     *
     * @return array
     */
    public function getDates()
    {
        return [
            'deleted_at'
        ];
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'content',
		'news_category_id',
		'slug',
        'deleted_at'
    ];

    /**
     * belongsTo NewsCategory
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo('App\Models\NewsCategory', 'news_category_id', 'id');
    }

    /**
     * hasMany NewsTag
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function newsTags()
    {
        return $this->hasMany('App\NewsTag', 'news_id', 'id');
    }

	function getImageAttribute() {
		$document = Document::where('model', 'News')->where('foreign_id', $this->id)->first();
		if ($document) {
			return $document->filename;
		} else {
			return '';
		}
	}

    function getRelatedNewsAttribute() {
        $news = News::where('id', '!=', $this->id)->where('news_category_id', $this->news_category_id)->limit(3)->orderBy('created_at', 'desc')->get();
        if ($news->count() == 3) {
            return $news;
        }
        $ids = [];
        foreach ($news as $n) {
            $ids[] = $n->id;
        }
        $more_news = News::whereNotIn('id', $ids)->where('news_category_id', '!=', $this->news_category_id)->limit(3 - $news->count())->orderBy('created_at', 'desc')->get();
        if ($more_news->count()) {
            return $news->merge($more_news);
        } else {
            return $news;
        }
    }

}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\News;
use App\Models\Document;
use DB;
use Auth;
use Validator;
use Input;
use Redirect;
use Illuminate\Support\Str;

class NewsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param  Request  $request
     * @return Response
     */
    public function index(Request $request)
    {
		$user = Auth::user();
		$this->authorize(new News);

        $news = DB::table('news')
			->select('news.*', 'news_categories.name as category_name')
			->leftJoin('news_categories', 'news.news_category_id', '=', 'news_categories.id')
            ->whereNull('news.deleted_at')
            ->orderBy('news.created_at', 'desc')
            ->paginate(config('admin.pagination'));

        return view('backend.news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  Request  $request
     * @return Response
     */
    public function create(Request $request)
    {
        $this->authorize(new News);
		extract($this->selects());
        return view('backend.news.create', compact('categories'));
    }

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$user = Auth::user();
        $this->authorize(new News);

		$rules = array(
			'title' => 'required',
			'content' => 'required',
			'news_category_id' => 'required',
		);

		$validator = Validator::make(Input::all(), $rules);
		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator->messages())->withInput();
		}

        $slug = Str::slug($request->get('title'));
        if (News::whereSlug($slug)->first()) {
			return Redirect::back()->withErrors(_('Ya existe una noticia con este título'))->withInput();
        }

		$news = new News;
		$news->title = $request->get('title');
		$news->news_category_id = $request->get('news_category_id');
		$news->content = $request->get('content');
		$news->slug = $slug;
		$news->save();

		$data = $request->all();
        if (!empty($data['filename'])) {
            $file = $data['filename'];
            $document = new Document;
            $document->name = '';
            $document->model = 'News';
            $document->foreign_id = $news->id;
            $document->filename = $file;
            $document->type = 'image';
            $document->save();
        }

		return redirect()->route('admin.news.index')->with('message', sprintf(_('Se ha creado la noticia %s'), $news->title));
	}

    /**
     * Show the form for editing a new resource.
     *
     * @param  Request  $request
     * @return Response
     */
    public function edit(Request $request, $id)
    {
		$news = News::findOrFail($id);
        $this->authorize($news);
		extract($this->selects());

		$document = Document::where('model', 'News')->where('foreign_id', $id)->first();
        return view('backend.news.edit', compact('news', 'categories', 'document'));
    }

	/**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
	    $user = Auth::user();
        $news = News::findOrFail($id);
        $this->authorize($news);

		$rules = array(
			'title' => 'required',
			'content' => 'required',
		);

		$validator = Validator::make(Input::all(), $rules);
		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator->messages())->withInput();
			// return Redirect::back()->with('error', _('No se pudo actualizar el evento'));
		}

		$news = new News;
		$news->title = $request->get('title');
		$news->news_category_id = $request->get('news_category_id');
		$news->content = $request->get('content');
		// $news->slug = Str::slug($request->get('title'));
		$news->save();

		$file = $request->get('filename');
		$document = new Document;
		$document->name = '';
		$document->model = 'News';
		$document->foreign_id = $news->id;
		$document->filename = $file;
		$document->type = 'image';
		$document->save();

        // $news->update($request->all());
        return Redirect::back()->with('message', sprintf(_('Se han actualizado los datos de la noticia %s'), $news->title));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news = News::findOrFail($id);
        $this->authorize($news);
		$title = $news->title;
        $news->delete();

        return redirect()->route('admin.news.index')->with('message', _("La noticia $title ha sido eliminada."));
    }

    /**
     * Returns list of tags and categories
     *
     * @return Array
     */
	private function selects() {
		/*
		$tags_list = DB::table('tags')->where('deleted_at', null)->get();
		$tags = array();
		foreach ($tags_list as $tag) {
			$tags[$tag->id] = $tag->name;
		}
		*/

		$category_list = DB::table('news_categories')->where('deleted_at', null)->get();
		$categories = array();
		foreach ($category_list as $category) {
			$categories[$category->id] = $category->name;
		}

		// return compact('tags', 'categories');
		return compact('categories');
	}

}

resources/views/frontend/news/index.blade.php
@section('pagina','blog')								{{-- id de la pagina para el body --}}
@section('title','Blog')           			 			{{-- titulo de la pagina --}}
@section('blog_act','active')                    		{{-- activacion menu top --}}
@section('content')                               		{{-- contendido pagina --}}
<!-- BEGIN DESTACADAS -->
<div class="section bg-blanco" id="destacados">
	<div class="container">
		<div class="latobold12 text-uppercase">
			blog emprestamo
		</div>
		<div class="row margTop40" id="contNot">
			@foreach ($news as $i => $n)
				@if ($i <= 1)
					<div class="col-md-6 col-sm-12 col-xs-12 margBot40">
						<a href="{{ route('news.show', [$n->slug]) }}"><div class="imagen" style="background: url({{ AssetUrl::get('Document', 'image', $n->image, 500, 400) }}) no-repeat center center / cover"></div></a>
						<div class="latobold12 margTop30"><span class="naranja text-uppercase">{{ $n->category->name  }}</span> <span class="negro">| {{ Functions::shortDate($n->created_at) }}</span></div>
						<div class="latoligth34 margTop20"><a href="{{ route('news.show', [$n->slug]) }}" class="negro">{{ $n->title }}</a></div>
					</div>
				@else
					<div class="col-md-4 margBot40">
						<a href="{{ route('news.show', [$n->slug]) }}"><div class="imagenmed" style="background: url({{ AssetUrl::get('Document', 'image', $n->image, 500, 400) }}) no-repeat center center / cover"></div></a>
						<div class="latobold12 margTop30"><span class="naranja text-uppercase">{{ $n->category->name }}</span> <span class="negro">| {{ Functions::shortDate($n->created_at) }}</span></div>
						<div class="latoligth34 margTop20"><a href="{{ route('news.show', [$n->slug]) }}" class="negro">{{ $n->title }}</a></div>
					</div>
				@endif
			@endforeach
		</div>
		<!-- END LISTADO NOTICIAS -->

		<div class="row text-center margTop30">
			<a id="loadMoreNews" class="btn btn-transparente naranja text-uppercase" href="javascript:;"> cargar más noticias</a>
		</div>
	</div>
</div>
<!-- END NOTICIAS RESTO -->
@endsection

@extends('frontend.layouts.default')

resources/views/frontend/news/show.blade.php
@section('pagina','blog-det')							{{-- id de la pagina para el body --}}
@section('title',$news->title)           			 			{{-- titulo de la pagina --}}
@section('blog_act','active')                    		{{-- activacion menu top --}}


@section('scripts_pagina')								{{-- js plugins inscluidos en la pagina (indept de los core) --}}
<script type="text/javascript" src="/assets/plugins/social/jssocials.min.js"></script>
<script type="text/javascript" src="/assets/scripts/blog.js"></script>
@endsection

@section('css_pagina')									{{-- css especifico de la pagina --}}
<link href="/assets/css/jssocials.css" rel="stylesheet" type="text/css">
<link href="/assets/css/jssocials-theme-flat.css" rel="stylesheet" type="text/css">
@endsection

@section('js_pagina')									{{-- script de la pagina --}}
@parent
Blog.init();
@endsection

@section('content')                               		{{-- contendido pagina --}}
<!-- BEGIN NOTICIA -->
<div class="section bg-blanco animatedParent animateOnce" id="noticia">
	<div class="container">
		<div class="latobold12 text-uppercase">
            blog emprestamo | {{ $news->title }}
		</div>
		<div class="row margTop40">
			<div class="col-md-8 col-md-push-2 col-sm-12 col-xs-12 margBot40 animated fadeIn">
				<div class="imagen" style="background: url({{ AssetUrl::get('Document', 'image', $news->image, 675, 450) }}) no-repeat center center / cover"></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-push-3 fechacat">
                <div class="latobold12 titular"><span class="naranja text-uppercase">{{ $news->category->name }}</span> <span class="negro">| {{ Functions::shortDate($news->created_at) }}</span></div>

				<!-- BEGIN DATOS NOTICIA -->
                <div class="latoligth34 margTop20">{{ $news->title }}</div>
				<div class="latoligth15 margTop20">
                    {!! $news->content !!}
				</div>
				<div class="latoligth34 text-center margTop60">Comparte la noticia</div>
				<!-- END DATOS NOTICIA -->

				<!-- BEGIN SOCIAL SHARE -->
				<div class="margTop20 text-center">
					<div id="social"></div>
				</div>
				<!-- END SOCIAL SHARE -->

			</div>
		</div>
		<div class="row margTop90">
			<div class="latobold16 text-center text-uppercase margBot30">noticias relacionadas</div>
            @foreach ($news->related_news as $n)
                <div class="col-md-4 margBot40">
                    <a href="{{ route('news.show', [$n->slug]) }}"><div class="imagenmed" style="background: url({{ AssetUrl::get('Document', 'image', $n->image, 675, 450) }}) no-repeat center center / cover"></div></a>
                    <div class="latobold12 margTop30"><span class="naranja text-uppercase">{{ $n->category->name }}</span> <span class="negro">| {{ Functions::shortDate($n->created_at) }}</span></div>
                    <div class="latoligth21 margTop20"><a href="{{ url('/blog/view') }}" class="negro">{{ $n->title }}</a></div>
                </div>
            @endforeach
		</div>
	</div>
</div>
<!-- END NOTICIA -->
@endsection

@extends('frontend.layouts.default')